### ISSUE TITLE
Node 7.8.0 requirement

### ISSUE THREAD

**Issue by benswinburne** [gudwin/botbuilder-formflow#2]
Which part of the codebase calls for this engine dependency? I am running my bot in AWS lambda and therefore can only go as high as Node 6.10.3 unfortunately. I was hoping that this dependency is erroneous or something simple enough that i could make it compatible with an older node version.

**Comment by gudwin** [comment]
Actually, there are no requirements to node.js engine from the library. I will remove that constraint in next release, that will happen in a days.

**Comment by gudwin** [comment]
Finally, 0.5.0 version released. 
Engine dependency removed.

https://github.com/gudwin/botbuilder-formflow/releases/tag/0.5.0
